<a href="https://colab.research.google.com/github/FranciscoFoz/Bibliotecario_em_Ciencia_de_Dados/blob/main/Bibliotecario__Ciencia_de_dados_Algebra_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = white> Vetores

Este notebook faz parte de um projeto iniciado por mim, Francisco Foz, integrante do time Alura Stars. Com o objetivo de auxiliar na disseminação da informação em Ciência de Dados para a área da biblioteconomia. Utilizando do livro "Data Science do zero" de Joel Grus.
Abordarei alguns conceitos básicos de algebra linear para data science.


In [ ]:
import numpy as np


In [ ]:
PX = np.array([10, 3])
P1 = np.array([2, 3])
P2 = np.array([3, 1])
P3 = np.array([12, 5])
P4 = np.array([18, 2])

In [ ]:
np.linalg.norm(PX - P4)

8.06225774829855

In [ ]:
dist_P1 = np.linalg.norm(PX - P1)
dist_P2 = np.linalg.norm(PX - P2)
dist_P3 = np.linalg.norm(PX - P3)
dist_P4 = np.linalg.norm(PX - P4)

In [ ]:
valores = np.array([dist_P1, dist_P2, dist_P3, dist_P4])
chaves = np.array(['P1','P2','P3','P4'])

Distancias = sorted(list(zip(valores,chaves)))
Distancias

[(2.8284271247461903, 'P3'),
 (7.280109889280518, 'P2'),
 (8.0, 'P1'),
 (8.06225774829855, 'P4')]

## Operações com Vetores

In [ ]:
B = [50,120]
M = [100,150]
B + M

[50, 120, 100, 150]

Adição

In [ ]:
biblioteconomia = np.array([[50,120]])
matematica = np.array([[100,150]])
total = biblioteconomia + matematica
total

array([[150, 270]])

Subtração

In [ ]:
Total = np.array([[10220,12250]])
medicina = np.array([[1020,9250]])
total = Total - medicina
total

array([[9200, 3000]])

Soma Escalar

In [ ]:
filosofia = np.array([250,233])
filosofia = filosofia + 2
filosofia

array([252, 235])

Multiplicação


In [ ]:
quantidade_exemplares = np.array([10,20,15,2,23])
quantidade_emprestimos_titulo = np.array([2,10,3,5,4])
total_emprestimos = quantidade_exemplares * quantidade_emprestimos_titulo
total_emprestimos

array([ 20, 200,  45,  10,  92])

Multiplicação Escalar

In [ ]:
emprestimos_2021_cursos = np.array([200,350,169,1120,568,970])
projecao_emprestimos_2022 = emprestimos_2021_cursos + (emprestimos_2021_cursos * 0.1)
projecao_emprestimos_2022

array([ 220. ,  385. ,  185.9, 1232. ,  624.8, 1067. ])

Testes condicionais


In [ ]:
outliers = projecao_emprestimos_2022 > 1000
outliers

array([False, False, False,  True, False,  True])

##Matrizes


In [ ]:
                #Acessos  #Emprestimos
biblioteconomia = [10220, 95860]
ciencias_socias = [7220,  7086]
filosofia       = [6523,  6086]
historia        = [10130, 9860]
pedagogia       = [12356, 11284]
arquivologia    = [15423, 9764]

In [ ]:
E_2020 = np.matrix([biblioteconomia, ciencias_socias , filosofia , historia , pedagogia , arquivologia])
E_2020

matrix([[10220, 95860],
        [ 7220,  7086],
        [ 6523,  6086],
        [10130,  9860],
        [12356, 11284],
        [15423,  9764]])

In [ ]:
np.shape(E_2020)

(6, 2)

In [87]:
biblioteconomia = [2000, 201]
ciencias_socias = [550, 365]
filosofia       = [856,  423]
historia        = [412, 120]
pedagogia       = [980, 652]
arquivologia    = [2541, 98]

In [88]:
E_2021 = np.matrix([biblioteconomia, ciencias_socias , filosofia , historia , pedagogia , arquivologia])
E_2021

matrix([[2000,  201],
        [ 550,  365],
        [ 856,  423],
        [ 412,  120],
        [ 980,  652],
        [2541,   98]])

In [ ]:
E_2020

matrix([[10220, 95860],
        [ 7220,  7086],
        [ 6523,  6086],
        [10130,  9860],
        [12356, 11284],
        [15423,  9764]])

Soma

In [89]:
E_2020 + E_2021

matrix([[12220, 96061],
        [ 7770,  7451],
        [ 7379,  6509],
        [10542,  9980],
        [13336, 11936],
        [17964,  9862]])

Subtração

In [90]:
E_2021 - E_2020

matrix([[ -8220, -95659],
        [ -6670,  -6721],
        [ -5667,  -5663],
        [ -9718,  -9740],
        [-11376, -10632],
        [-12882,  -9666]])

Transposição

In [94]:
E_2020.getT()

matrix([[10220,  7220,  6523, 10130, 12356, 15423],
        [95860,  7086,  6086,  9860, 11284,  9764]])

In [93]:
E_2020 * 0.2

matrix([[ 2044. , 19172. ],
        [ 1444. ,  1417.2],
        [ 1304.6,  1217.2],
        [ 2026. ,  1972. ],
        [ 2471.2,  2256.8],
        [ 3084.6,  1952.8]])